/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/assessments/evaluate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Evaluate
     * @description Validate the input, run the engine, return the full result.
     *
     *     Stateless and deterministic: an identical request body against an
     *     identical methodology version yields a byte-identical response body.
     */
    post: operations['evaluate_api_assessments_evaluate_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/assessments/validate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Validate
     * @description Dry-run validation of a partial questionnaire state (D-028).
     */
    post: operations['validate_api_assessments_validate_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/geo/basemap': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Basemap
     * @description Return the bundled 1:110m country outlines the offline map draws.
     */
    get: operations['basemap_api_geo_basemap_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/geo/lookup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Lookup
     * @description Answer the three questions a map may answer about a location.
     *
     *     Returns suggestions, not answers. The caller applies each one only where
     *     the user has not already answered, and marks what it applies as autofilled
     *     (D-047.2) — an autofilled value never overwrites an answer already given.
     */
    post: operations['lookup_api_geo_lookup_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/geo/places': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Places
     * @description Search the bundled populated-places index by name (v2.2, D-049.6).
     *
     *     Navigation, not autofill: a result is somewhere for the map to move to,
     *     and selecting one fills in no answer. Answered entirely from bundled
     *     public-domain data — this is the navigation aid a deployment without
     *     configured imagery has.
     */
    get: operations['places_api_geo_places_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/meta': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Meta
     * @description Engine version, methodology version, licence, and tile configuration.
     *
     *     ``tiles`` is how the browser learns what the deployer configured
     *     (D-049.2): the server never requests a tile itself, it only relays the
     *     template and the credit that must accompany it (D-049.3).
     */
    get: operations['meta_api_meta_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/methodology': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Methodology
     * @description Formulas, weights, factors, and defaults, with the methodology version.
     */
    get: operations['methodology_api_methodology_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Projects
     * @description All projects, most recently updated first.
     */
    get: operations['list_projects_api_projects_get'];
    put?: never;
    /** Create Project */
    post: operations['create_project_api_projects_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{project_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Project */
    get: operations['get_project_api_projects__project_id__get'];
    put?: never;
    post?: never;
    /** Delete Project */
    delete: operations['delete_project_api_projects__project_id__delete'];
    options?: never;
    head?: never;
    /** Update Project */
    patch: operations['update_project_api_projects__project_id__patch'];
    trace?: never;
  };
  '/api/projects/{project_id}/assessments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Assessment */
    post: operations['create_assessment_api_projects__project_id__assessments_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{project_id}/assessments/{assessment_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Assessment */
    get: operations['get_assessment_api_projects__project_id__assessments__assessment_id__get'];
    put?: never;
    post?: never;
    /** Delete Assessment */
    delete: operations['delete_assessment_api_projects__project_id__assessments__assessment_id__delete'];
    options?: never;
    head?: never;
    /** Update Assessment */
    patch: operations['update_assessment_api_projects__project_id__assessments__assessment_id__patch'];
    trace?: never;
  };
  '/api/projects/{project_id}/assessments/{assessment_id}/duplicate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Duplicate Assessment
     * @description Create a comparison draft from an existing assessment (D-021).
     */
    post: operations['duplicate_assessment_api_projects__project_id__assessments__assessment_id__duplicate_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{project_id}/assessments/{assessment_id}/evaluate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Evaluate Assessment
     * @description Run the engine on the stored draft input and persist the result.
     *
     *     An explicit user action (OQ-15): refused once a result exists, because a
     *     stored result is never recomputed — re-running means creating a new
     *     assessment.
     */
    post: operations['evaluate_assessment_api_projects__project_id__assessments__assessment_id__evaluate_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{project_id}/assessments/{assessment_id}/report.pdf': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Report Pdf
     * @description The 2-page PDF report of a stored, evaluated assessment.
     */
    get: operations['report_pdf_api_projects__project_id__assessments__assessment_id__report_pdf_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{project_id}/assessments/{assessment_id}/report.xlsx': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Report Xlsx
     * @description The XLSX workbook (Inputs, Results, Assumptions & Warnings).
     */
    get: operations['report_xlsx_api_projects__project_id__assessments__assessment_id__report_xlsx_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/typologies': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Typologies
     * @description The full library: 18 cited archetypes and the 110 entries inheriting them.
     *
     *     ``resolved`` carries each entry merged with its archetype — the flat view
     *     the picker renders and the engine scores — while ``archetypes`` carries the
     *     citations, so the interface can show which evidence class a card's numbers
     *     came from without inferring anything.
     */
    get: operations['typologies_api_typologies_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/typologies/available': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Available
     * @description The entries offered for this site (D-043, D-044.1).
     *
     *     Availability guides selection and never blocks it (D-019): an entry absent
     *     from this list stays fully selectable, and the engine scores it with the
     *     honest suitability flags of D-009. This endpoint answers "what should the
     *     picker show first", not "what is permitted".
     */
    get: operations['available_api_typologies_available_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AdjustmentBlock
     * @description Site adjustment factor and its four derived conditions (5.4).
     */
    AdjustmentBlock: {
      canopy: components['schemas']['AdjustmentCondition'];
      climate: components['schemas']['AdjustmentCondition'];
      /** Factor */
      factor: number;
      scale: components['schemas']['AdjustmentCondition'];
      soil_water: components['schemas']['AdjustmentCondition'];
    };
    /**
     * AdjustmentCondition
     * @description One derived site condition and the factor it resolved to.
     */
    AdjustmentCondition: {
      /** Detail */
      detail?: string | null;
      /** Factor */
      factor: number;
      /**
       * Level
       * @enum {string}
       */
      level: 'poor' | 'moderate' | 'good' | 'excellent' | 'unknown';
    };
    /**
     * Archetype
     * @description One cited cooling evidence class (D-044).
     *
     *     Every performance value in the library lives here, with the citations that
     *     support it. The 110 catalogue entries carry no performance value of their
     *     own; each inherits exactly one archetype and the report names the evidence
     *     class it inherited from.
     */
    Archetype: {
      /** Archetype */
      archetype: string;
      /** Base Cooling Score */
      base_cooling_score: number;
      /** Building Energy Applicable */
      building_energy_applicable: boolean;
      /**
       * Category
       * @enum {string}
       */
      category: 'green' | 'building' | 'blue_green' | 'hybrid';
      /** Co Benefit Defaults */
      co_benefit_defaults: {
        [key: string]: string;
      };
      /** Display Name */
      display_name: string;
      /**
       * Evidence Confidence
       * @enum {string}
       */
      evidence_confidence: 'low' | 'medium' | 'high';
      /** Notes */
      notes?: string | null;
      /** Output Caveats */
      output_caveats?: string[];
      /**
       * Provenance
       * @enum {string}
       */
      provenance: 'existing' | 'new' | 'derived';
      /** Sources */
      sources: components['schemas']['Source'][];
      suitability: components['schemas']['Suitability'];
      /** Temp Reduction Max C */
      temp_reduction_max_c: number;
      /** Temp Reduction Min C */
      temp_reduction_min_c: number;
    };
    /** AssessmentCreate */
    AssessmentCreate: {
      /** Autofilled */
      autofilled?: {
        [key: string]: string;
      };
      /** Input */
      input?: {
        [key: string]: unknown;
      };
      /** Label */
      label: string;
    };
    /** AssessmentDuplicate */
    AssessmentDuplicate: {
      /** Label */
      label?: string | null;
    };
    /**
     * AssessmentInput
     * @description One site plus one proposed NbS intervention, as described by the user.
     *
     *     Required fields are those without which a documented formula cannot be
     *     evaluated at all; everything else is optional, and absence reduces
     *     confidence but never blocks the assessment.
     */
    AssessmentInput: {
      /** Access To Cool Outdoor Refuge */
      access_to_cool_outdoor_refuge?: ('low' | 'medium' | 'high' | 'unknown') | null;
      /** Access To Cooled Indoor Space */
      access_to_cooled_indoor_space?: ('low' | 'medium' | 'high' | 'unknown') | null;
      /** Annual Cooling Energy Demand Kwh */
      annual_cooling_energy_demand_kwh?: number | null;
      /**
       * Assessment Scale
       * @enum {string}
       */
      assessment_scale: 'city' | 'district' | 'neighbourhood' | 'site' | 'building';
      /** Capital Cost */
      capital_cost?: number | null;
      /**
       * Climate Zone
       * @enum {string}
       */
      climate_zone: 'tropical_wet' | 'tropical_dry' | 'arid' | 'semi_arid' | 'temperate' | 'other';
      /** Co Benefit Biodiversity */
      co_benefit_biodiversity?: ('low' | 'medium' | 'high' | 'very_high' | 'unknown') | null;
      /** Co Benefit Public Health */
      co_benefit_public_health?: ('low' | 'medium' | 'high' | 'very_high' | 'unknown') | null;
      /** Co Benefit Social Inclusion */
      co_benefit_social_inclusion?: ('low' | 'medium' | 'high' | 'very_high' | 'unknown') | null;
      /** Co Benefit Stormwater */
      co_benefit_stormwater?: ('low' | 'medium' | 'high' | 'very_high' | 'unknown') | null;
      /** Co Benefit Urban Quality */
      co_benefit_urban_quality?: ('low' | 'medium' | 'high' | 'very_high' | 'unknown') | null;
      /** Community Participation */
      community_participation?: ('low' | 'medium' | 'high' | 'very_high' | 'unknown') | null;
      /** Country */
      country?: string | null;
      /** Currency */
      currency?: string | null;
      /** Current Shade Level */
      current_shade_level?: ('very_low' | 'low' | 'medium' | 'high' | 'unknown') | null;
      /** Energy Price Per Kwh */
      energy_price_per_kwh?: number | null;
      /** Existing Green Cover Percent */
      existing_green_cover_percent?: number | null;
      /** Existing Tree Canopy Percent */
      existing_tree_canopy_percent?: number | null;
      /** Existing Woodland */
      existing_woodland?: ('yes' | 'no' | 'unknown') | null;
      /** Expected Maturity Period Years */
      expected_maturity_period_years?: number | null;
      /** Grid Emission Factor Kgco2E Per Kwh */
      grid_emission_factor_kgco2e_per_kwh?: number | null;
      /** Heat Exposure Level */
      heat_exposure_level?: ('low' | 'medium' | 'high' | 'very_high' | 'unknown') | null;
      /** Heat Index Concern */
      heat_index_concern?: ('low' | 'medium' | 'high' | 'very_high' | 'unknown') | null;
      /** Impervious Surface Percent */
      impervious_surface_percent?: number | null;
      /** Implementation Complexity */
      implementation_complexity?: ('low' | 'medium' | 'high' | 'unknown') | null;
      /** Includes Railway */
      includes_railway?: ('yes' | 'no' | 'unknown') | null;
      /** Intervention Area M2 */
      intervention_area_m2?: number | null;
      /** Irrigation Availability */
      irrigation_availability?: ('none' | 'occasional' | 'reliable' | 'unknown') | null;
      /** Land Use */
      land_use?:
        | (
            | 'street_corridor'
            | 'residential'
            | 'mixed_use'
            | 'commercial'
            | 'public_space'
            | 'park'
            | 'school'
            | 'campus'
            | 'healthcare'
            | 'memorial'
            | 'industrial'
            | 'other'
          )
        | null;
      /** Lst Anomaly C */
      lst_anomaly_c?: number | null;
      /** Maintenance Intensity */
      maintenance_intensity?: ('low' | 'medium' | 'high' | 'unknown') | null;
      /** Nbs Type */
      nbs_type: string[];
      /** Nearby Building Cooling Demand Relevant */
      nearby_building_cooling_demand_relevant?: ('yes' | 'no' | 'unknown') | null;
      /** New Canopy Area At Maturity M2 */
      new_canopy_area_at_maturity_m2?: number | null;
      /** Population Density */
      population_density?: ('low' | 'medium' | 'high' | 'very_high' | 'unknown') | null;
      /** Productive Governance */
      productive_governance?:
        ('community' | 'individual' | 'institutional' | 'commercial')[] | null;
      /** Project Name */
      project_name?: string | null;
      /** Public Accessibility */
      public_accessibility?: ('low' | 'medium' | 'high' | 'very_high' | 'unknown') | null;
      /** Safety Concern */
      safety_concern?: ('low' | 'medium' | 'high' | 'very_high' | 'unknown') | null;
      /** Site Area M2 */
      site_area_m2: number;
      /** Soil Availability */
      soil_availability?: ('none' | 'limited' | 'moderate' | 'high' | 'unknown') | null;
      /** Solar Exposure */
      solar_exposure?: ('low' | 'medium' | 'high' | 'very_high' | 'unknown') | null;
      /** Vulnerable Population Presence */
      vulnerable_population_presence?: ('low' | 'medium' | 'high' | 'very_high' | 'unknown') | null;
      /** Waterfront Type */
      waterfront_type?: ('lake' | 'river' | 'dry_river' | 'covered_river' | 'sea') | null;
    };
    /** AssessmentPatch */
    AssessmentPatch: {
      /** Autofilled */
      autofilled?: {
        [key: string]: string;
      } | null;
      /** Input */
      input?: {
        [key: string]: unknown;
      } | null;
      /** Label */
      label?: string | null;
    };
    /**
     * AssessmentResult
     * @description Everything the engine reports for one assessment run.
     *
     *     The top-level blocks are the PACKAGE's outputs. A single-intervention
     *     assessment is a package of one, so every top-level block equals its only
     *     component's and nothing about the single case changed shape.
     */
    AssessmentResult: {
      adjustment: components['schemas']['AdjustmentBlock'];
      /** Assumptions Applied */
      assumptions_applied: string[];
      co_benefits: components['schemas']['CoBenefitsBlock'];
      /** Components */
      components: components['schemas']['ComponentBlock'][];
      confidence: components['schemas']['ConfidenceBlock'];
      cooling: components['schemas']['CoolingBlock'];
      costs: components['schemas']['CostsBlock'];
      energy: components['schemas']['EnergyBlock'];
      /** Engine Version */
      engine_version: string;
      equity: components['schemas']['EquityBlock'];
      ghg: components['schemas']['GhgBlock'];
      heat_exposure: components['schemas']['HeatExposureBlock'];
      heat_priority: components['schemas']['HeatPriorityBlock'];
      /** Method Note */
      method_note: string;
      /** Methodology Version */
      methodology_version: string;
      opportunity: components['schemas']['OpportunityBlock'];
      package: components['schemas']['PackageBlock'];
      /** Recommendation */
      recommendation: string;
      suitability: components['schemas']['SuitabilityBlock'];
      typology: components['schemas']['TypologySummary'];
      vulnerability: components['schemas']['VulnerabilityBlock'];
      /** Warnings */
      warnings: string[];
    };
    /**
     * AssessmentView
     * @description A stored assessment plus the OQ-15 surfacing flag.
     *
     *     ``methodology_update_available`` is true when the stored result was
     *     produced under an older methodology version than the one currently loaded.
     *     The stored result itself is never recomputed; re-running is an explicit
     *     user action that creates a new assessment.
     */
    AssessmentView: {
      /** Assessment Id */
      assessment_id: string;
      /** Autofilled */
      autofilled?: {
        [key: string]: string;
      };
      /** Created At */
      created_at: string;
      /** Input */
      input: {
        [key: string]: unknown;
      };
      /** Label */
      label: string;
      /** Methodology Update Available */
      methodology_update_available: boolean;
      /** Result */
      result?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * Availability
     * @description When an entry is offered to the user (D-043, D-044.1).
     *
     *     Availability gates *selection*; it feeds no score. A condition that is
     *     ``None``/``False`` is ungated — notably the four constructed water features,
     *     which need no existing water body, and the woodland *creation* types, which
     *     need no existing woodland.
     */
    Availability: {
      /** Land Uses */
      land_uses: string[] | 'all';
      /**
       * Requires Existing Woodland
       * @default false
       */
      requires_existing_woodland: boolean;
      /** Requires Governance */
      requires_governance?: ('community' | 'individual' | 'institutional' | 'commercial') | null;
      /**
       * Requires Railway
       * @default false
       */
      requires_railway: boolean;
      /** Requires Waterfront */
      requires_waterfront?: ('lake' | 'river' | 'dry_river' | 'covered_river' | 'sea')[] | null;
      /** Scales */
      scales: ('city' | 'district' | 'neighbourhood' | 'site' | 'building')[];
    };
    /**
     * AvailableTypologies
     * @description ``GET /api/typologies/available`` (D-043, D-044.1).
     *
     *     A declared response model rather than a bare mapping, so the shape is part
     *     of the OpenAPI schema and the frontend's generated types can check it —
     *     the same contract every other endpoint offers (D-030).
     *
     *     ``nbs_types`` lists what the matrix offers, in library order. It is not a
     *     permission list: an entry absent from it stays fully selectable (D-019),
     *     and the engine scores it with the honest suitability flags of D-009.
     */
    AvailableTypologies: {
      /** Assessment Scale */
      assessment_scale: string;
      /** Composes Packages */
      composes_packages: boolean;
      /** Count */
      count: number;
      /** Land Use */
      land_use: string | null;
      /** Nbs Types */
      nbs_types: string[];
      /** Version */
      version: string;
      /** Warn Above Components */
      warn_above_components: number;
    };
    /**
     * BlockConfidencePreview
     * @description Live confidence for one output block (UX specification section 4).
     */
    BlockConfidencePreview: {
      /** Completeness Percent */
      completeness_percent: number;
      hint: components['schemas']['ConfidenceHint'] | null;
      /**
       * Level
       * @enum {string}
       */
      level: 'low' | 'medium' | 'high';
    };
    /**
     * CoBenefitsBlock
     * @description Co-benefit Score and its five sub-indicators.
     */
    CoBenefitsBlock: {
      /** Biodiversity */
      biodiversity: number;
      /** Public Health */
      public_health: number;
      /** Score */
      score: number;
      /** Social Inclusion */
      social_inclusion: number;
      /** Stormwater */
      stormwater: number;
      /** Urban Quality */
      urban_quality: number;
    };
    /**
     * ComponentBlock
     * @description One package component, scored individually (D-038).
     *
     *     Every component is scored on its own values and reported on its own terms:
     *     its adjustment, its suitability and flags, its cooling range. Nothing here
     *     is averaged with a sibling — the package-level blocks are derived from
     *     these by the stated combination rules, never the other way round.
     */
    ComponentBlock: {
      adjustment: components['schemas']['AdjustmentBlock'];
      co_benefits: components['schemas']['CoBenefitsBlock'];
      cooling: components['schemas']['CoolingBlock'];
      /** Is Representative */
      is_representative: boolean;
      suitability: components['schemas']['SuitabilityBlock'];
      typology: components['schemas']['TypologySummary'];
    };
    /**
     * ConfidenceBlock
     * @description Branched per-block confidence (D-011/OQ-09, D-024).
     */
    ConfidenceBlock: {
      /** Completeness Percent */
      completeness_percent: {
        [key: string]: number;
      };
      /**
       * Cooling
       * @enum {string}
       */
      cooling: 'low' | 'medium' | 'high';
      /** Cooling Capped By Evidence */
      cooling_capped_by_evidence: boolean;
      /**
       * Economic
       * @enum {string}
       */
      economic: 'low' | 'medium' | 'high';
      /**
       * Energy
       * @enum {string}
       */
      energy: 'low' | 'medium' | 'high';
      /**
       * Equity
       * @enum {string}
       */
      equity: 'low' | 'medium' | 'high';
      /**
       * Overall
       * @enum {string}
       */
      overall: 'low' | 'medium' | 'high';
    };
    /**
     * ConfidenceHint
     * @description The highest-value missing field group for one block (D-028).
     *
     *     ``fields`` lists the group's alternative fields (usually one; the heat
     *     signal slot offers two). ``raises_level_to`` is the level the block reaches
     *     if any of them is answered, or ``None`` when no single completion raises
     *     the level and the group is simply the first unsupplied one in configured
     *     order.
     */
    ConfidenceHint: {
      /** Fields */
      fields: string[];
      /** Raises Level To */
      raises_level_to: ('low' | 'medium' | 'high') | null;
    };
    /**
     * ConfidencePreview
     * @description Per-block confidence preview, computed by ``nature_cooling.engine.confidence``.
     */
    ConfidencePreview: {
      cooling: components['schemas']['BlockConfidencePreview'];
      /** Cooling Capped By Evidence */
      cooling_capped_by_evidence: boolean;
      economic: components['schemas']['BlockConfidencePreview'];
      energy: components['schemas']['BlockConfidencePreview'];
      equity: components['schemas']['BlockConfidencePreview'];
      /**
       * Overall
       * @enum {string}
       */
      overall: 'low' | 'medium' | 'high';
    };
    /**
     * CoolingBlock
     * @description Cooling Potential Score and clipped temperature range (5.5, D-008).
     */
    CoolingBlock: {
      /** Delta T Max C */
      delta_t_max_c: number;
      /** Delta T Midpoint C */
      delta_t_midpoint_c: number;
      /** Delta T Min C */
      delta_t_min_c: number;
      /**
       * Heat Index Improvement
       * @enum {string}
       */
      heat_index_improvement: 'low' | 'medium' | 'high';
      /** Potential Score */
      potential_score: number;
      /** Shade Potential Percent */
      shade_potential_percent: number | null;
      /**
       * Shade Potential Status
       * @enum {string}
       */
      shade_potential_status: 'calculated' | 'not_estimated';
      /** Time To Benefit */
      time_to_benefit: ('immediate' | 'short_term' | 'medium_term' | 'long_term') | null;
      /**
       * Time To Benefit Status
       * @enum {string}
       */
      time_to_benefit_status: 'derived' | 'not_estimated';
    };
    /**
     * CostsBlock
     * @description Cost outputs: savings, payback, derived feasibility, readiness (5.8).
     */
    CostsBlock: {
      /** Annual Savings Max */
      annual_savings_max: number | null;
      /** Annual Savings Min */
      annual_savings_min: number | null;
      /**
       * Annual Savings Status
       * @enum {string}
       */
      annual_savings_status: 'calculated' | 'energy_not_calculated' | 'missing_energy_price';
      /** Cost Feasibility Score */
      cost_feasibility_score: number | null;
      /**
       * Cost Feasibility Status
       * @enum {string}
       */
      cost_feasibility_status: 'derived' | 'not_estimated';
      /** Currency */
      currency: string | null;
      /** Investment Readiness */
      investment_readiness: ('low' | 'medium' | 'high') | null;
      /**
       * Investment Readiness Status
       * @enum {string}
       */
      investment_readiness_status: 'derived' | 'not_estimated';
      /** Payback Bracket */
      payback_bracket: ('short' | 'medium' | 'long' | 'very_long') | null;
      /**
       * Payback Status
       * @enum {string}
       */
      payback_status: 'calculated' | 'missing_capital_cost' | 'annual_savings_unavailable';
      /** Payback Years Central */
      payback_years_central: number | null;
      /** Payback Years Max */
      payback_years_max: number | null;
      /** Payback Years Min */
      payback_years_min: number | null;
    };
    /**
     * EnergyBlock
     * @description Derived cooling-energy savings (5.6, D-015).
     */
    EnergyBlock: {
      /** Savings Max Kwh Per Year */
      savings_max_kwh_per_year: number | null;
      /** Savings Min Kwh Per Year */
      savings_min_kwh_per_year: number | null;
      /**
       * Status
       * @enum {string}
       */
      status:
        | 'calculated'
        | 'not_applicable'
        | 'missing_energy_demand'
        | 'typology_not_applicable'
        | 'relevance_not_confirmed';
      /** Status Message */
      status_message: string;
    };
    /**
     * EquityBlock
     * @description Equity Score (reported with its own confidence; not aggregated).
     *
     *     The Equity Score deliberately does not enter the final aggregation:
     *     equity influences the headline score through the Vulnerability Score
     *     instead. This is disclosed in the Methodology Report.
     */
    EquityBlock: {
      /** Participation Relevance */
      participation_relevance: number;
      /** Public Accessibility */
      public_accessibility: number;
      /** Safety Comfort */
      safety_comfort: number;
      /** Score */
      score: number;
      /** Vulnerable User Benefit */
      vulnerable_user_benefit: number;
    };
    /**
     * FieldIssue
     * @description One validation error, addressed to the form field it belongs to.
     */
    FieldIssue: {
      /** Field */
      field: string;
      /** Message */
      message: string;
    };
    /**
     * GeoClimate
     * @description The climate zone a point resolved to, and the class it came from.
     */
    GeoClimate: {
      /** Attribution */
      attribution: string;
      /** Koppen Class */
      koppen_class: string | null;
      /** Note */
      note: string;
      /** Resolution Caveat */
      resolution_caveat: string;
      /** Source Key */
      source_key: string;
      /** Zone */
      zone: string | null;
    };
    /**
     * GeoCountry
     * @description The country a point resolved to, and how the lookup reached it.
     */
    GeoCountry: {
      /** Attribution */
      attribution: string;
      /** Iso A2 */
      iso_a2: string | null;
      /** Iso A3 */
      iso_a3: string | null;
      /** Matched */
      matched: string;
      /** Name */
      name: string | null;
      /** Source Key */
      source_key: string;
    };
    /**
     * GeoLookupRequest
     * @description ``POST /api/geo/lookup`` — what a map click can honestly answer (D-047).
     *
     *     ``boundary`` is the polygon the user drew, as ``[longitude, latitude]``
     *     pairs. When it is absent the user placed a point rather than drawing a
     *     site, and no area is returned.
     */
    GeoLookupRequest: {
      /** Boundary */
      boundary?: number[][] | null;
      /** Latitude */
      latitude: number;
      /** Longitude */
      longitude: number;
    };
    /**
     * GeoLookupResponse
     * @description ``POST /api/geo/lookup``.
     *
     *     Every value is a suggestion. The interface applies each one only where the
     *     user has not already answered, marks what it applied as autofilled, and
     *     lets any of them be overridden (D-047.2).
     */
    GeoLookupResponse: {
      climate: components['schemas']['GeoClimate'];
      country: components['schemas']['GeoCountry'];
      /** Latitude */
      latitude: number;
      /** Longitude */
      longitude: number;
      /** Site Area M2 */
      site_area_m2: number | null;
    };
    /**
     * GhgBlock
     * @description Greenhouse gas emissions avoided (5.7).
     */
    GhgBlock: {
      /** Avoided Max Kgco2E Per Year */
      avoided_max_kgco2e_per_year: number | null;
      /** Avoided Min Kgco2E Per Year */
      avoided_min_kgco2e_per_year: number | null;
      /** Emission Factor Kgco2E Per Kwh */
      emission_factor_kgco2e_per_kwh: number | null;
      /** Emission Factor Origin */
      emission_factor_origin: ('user_supplied' | 'country_default') | null;
      /**
       * Status
       * @enum {string}
       */
      status: 'calculated' | 'missing_emission_factor' | 'energy_not_calculated';
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /**
     * HeatExposureBlock
     * @description Heat Exposure Score (Methodology Report 5.1).
     */
    HeatExposureBlock: {
      /**
       * Path
       * @enum {string}
       */
      path: 'data_rich' | 'data_poor';
      /** Score */
      score: number;
    };
    /**
     * HeatPriorityBlock
     * @description Heat Priority Index (Methodology Report 5.3).
     */
    HeatPriorityBlock: {
      /**
       * Category
       * @enum {string}
       */
      category: 'low' | 'medium' | 'high' | 'critical';
      /** Score */
      score: number;
    };
    /**
     * MetaResponse
     * @description ``GET /api/meta``.
     */
    MetaResponse: {
      /** Engine Version */
      engine_version: string;
      /** License */
      license: string;
      /** Methodology Version */
      methodology_version: string;
      tiles: components['schemas']['TileSource'] | null;
    };
    /**
     * OpportunityBlock
     * @description NbS Cooling Opportunity Score (5.9), with full weight transparency.
     */
    OpportunityBlock: {
      /**
       * Category
       * @enum {string}
       */
      category: 'low' | 'moderate' | 'strong' | 'high_priority';
      /** Components */
      components: components['schemas']['OpportunityComponent'][];
      /** Excluded Components */
      excluded_components: string[];
      /** Score */
      score: number;
    };
    /**
     * OpportunityComponent
     * @description One component of the final aggregation, with the weight applied.
     */
    OpportunityComponent: {
      /** Applied Weight */
      applied_weight: number;
      /** Name */
      name: string;
      /** Nominal Weight */
      nominal_weight: number;
      /** Score */
      score: number;
    };
    /**
     * PackageBlock
     * @description How the package's headline outputs were combined (D-038, D-044.4).
     *
     *     The combination rules, and why each is what it is:
     *
     *     * **Temperature is capped at the best-evidenced component, never summed.**
     *       No retrieved source quantifies super-additive cooling from combining
     *       measures (D-014), so a package is reported at its representative
     *       component's adjusted range. Note that ``min(max_i t_i, t_representative)``
     *       and ``t_representative`` are the same number, since the representative's
     *       ceiling can never exceed the maximum over components — the cap and the
     *       selection are one rule, not two.
     *     * **Co-benefits take the union**: the maximum per dimension across
     *       components, each still carrying its own component's citation.
     *     * **Suitability takes the minimum.** A package is no more deliverable here
     *       than its least suitable component; averaging would let a well-fitting
     *       component conceal one that cannot be built on this site, which is what
     *       D-009 exists to prevent.
     *     * **Energy follows the best-evidenced component that is building-energy
     *       applicable**, so the derivation still traces to exactly one component and
     *       is never summed.
     *     * **Costs sum**, which is the user's single ``capital_cost`` entered for the
     *       whole package (see the field reference).
     */
    PackageBlock: {
      /** Co Benefit Rule */
      co_benefit_rule: string;
      /** Component Count */
      component_count: number;
      /** Cooling Rule */
      cooling_rule: string;
      /** Cost Rule */
      cost_rule: string;
      /** Energy Component Nbs Type */
      energy_component_nbs_type: string | null;
      /** Representative Nbs Type */
      representative_nbs_type: string;
      /** Representative Reason */
      representative_reason: string;
      /** Suitability Rule */
      suitability_rule: string;
    };
    /**
     * PlaceResult
     * @description One place-search match (v2.2, D-049.6): a name and somewhere to move
     *     the map to. Never an answer to any questionnaire field.
     */
    PlaceResult: {
      /** Admin */
      admin: string;
      /** Latitude */
      latitude: number;
      /** Longitude */
      longitude: number;
      /** Name */
      name: string;
      /** Population */
      population: number;
    };
    /**
     * PlaceSearchResponse
     * @description ``GET /api/geo/places`` — offline navigation by name.
     */
    PlaceSearchResponse: {
      /** Attribution */
      attribution: string;
      /** Query */
      query: string;
      /** Results */
      results: components['schemas']['PlaceResult'][];
    };
    /** ProjectCreate */
    ProjectCreate: {
      /** Name */
      name: string;
      /** Site */
      site?: {
        [key: string]: unknown;
      };
    };
    /** ProjectPatch */
    ProjectPatch: {
      /** Name */
      name?: string | null;
      /** Site */
      site?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * ProjectSummary
     * @description ``GET /api/projects`` list entry.
     */
    ProjectSummary: {
      /** Assessment Count */
      assessment_count: number;
      /** Created At */
      created_at: string;
      /** Name */
      name: string;
      /** Project Id */
      project_id: string;
      /** Updated At */
      updated_at: string;
    };
    /**
     * ProjectView
     * @description A project document plus the current methodology version, for OQ-15.
     *
     *     ``migrated_notes`` itemises any storage migration applied when this
     *     document was read, so a user whose saved drafts were reshaped is told what
     *     changed rather than discovering it (D-029, D-044.2).
     */
    ProjectView: {
      /** Assessments */
      assessments: components['schemas']['AssessmentView'][];
      /** Created At */
      created_at: string;
      /** Current Methodology Version */
      current_methodology_version: string;
      /** Migrated Notes */
      migrated_notes?: string[];
      /** Name */
      name: string;
      /** Project Id */
      project_id: string;
      /** Schema Version */
      schema_version: number;
      /** Site */
      site: {
        [key: string]: unknown;
      };
      /** Updated At */
      updated_at: string;
    };
    /**
     * Source
     * @description A citation supporting a configuration value.
     */
    Source: {
      /** Finding */
      finding: string;
      /** Key */
      key: string;
    };
    /**
     * Suitability
     * @description Conditions under which a typology is considered unsuitable for a site.
     */
    Suitability: {
      /** Minimum Site Area M2 */
      minimum_site_area_m2: number;
      /**
       * Requires Irrigation
       * @enum {string}
       */
      requires_irrigation: 'none' | 'occasional' | 'reliable';
      /**
       * Requires Soil
       * @enum {string}
       */
      requires_soil: 'none' | 'limited' | 'moderate' | 'high';
      /** Unsuitable Climate Zones */
      unsuitable_climate_zones?: string[];
    };
    /**
     * SuitabilityBlock
     * @description NbS Suitability Score, its sub-indicators, and hard flags (D-022).
     */
    SuitabilityBlock: {
      /** Flags */
      flags: components['schemas']['SuitabilityFlag'][];
      /** Maintenance */
      maintenance: number;
      /** Score */
      score: number;
      /** Soil */
      soil: number;
      /** Space */
      space: number;
      /** Suitable */
      suitable: boolean;
      /** Urban Context */
      urban_context: number;
      /** Water */
      water: number;
    };
    /**
     * SuitabilityFlag
     * @description A hard 'not suitable for this site' condition (D-009).
     */
    SuitabilityFlag: {
      /**
       * Code
       * @enum {string}
       */
      code:
        | 'below_minimum_area'
        | 'insufficient_soil'
        | 'insufficient_irrigation'
        | 'unsuitable_climate';
      /** Message */
      message: string;
    };
    /**
     * SuitabilityOverride
     * @description A per-entry departure from the archetype's suitability conditions.
     *
     *     Permitted only where the catalogue's own description of the entry makes an
     *     inherited value plainly wrong (D-044.3); every replacement value is one
     *     already present in the cited v1.1 library, so no new number enters the
     *     methodology through an override.
     */
    SuitabilityOverride: {
      /** Minimum Site Area M2 */
      minimum_site_area_m2?: number | null;
      /** Requires Irrigation */
      requires_irrigation?: ('none' | 'occasional' | 'reliable') | null;
      /** Requires Soil */
      requires_soil?: ('none' | 'limited' | 'moderate' | 'high') | null;
    };
    /**
     * TileSource
     * @description The deployment's configured tile source (v2.2, D-049).
     *
     *     Both halves travel together by construction: the application refuses to
     *     start with a URL and no attribution, so imagery can never reach a browser
     *     without the credit its licence requires (D-049.2).
     */
    TileSource: {
      /** Attribution */
      attribution: string;
      /** Url Template */
      url_template: string;
    };
    /**
     * Typology
     * @description One catalogue entry resolved against its archetype.
     *
     *     This is the flat view every scoring module consumes, and the shape the API
     *     serves. ``archetype`` and ``evidence_provenance`` are reported so a result
     *     can always name the evidence class its numbers came from.
     */
    Typology: {
      /** Archetype */
      archetype: string;
      /** Archetype Display Name */
      archetype_display_name: string;
      availability: components['schemas']['Availability'];
      /** Base Cooling Score */
      base_cooling_score: number;
      /** Building Energy Applicable */
      building_energy_applicable: boolean;
      /**
       * Category
       * @enum {string}
       */
      category: 'green' | 'building' | 'blue_green' | 'hybrid';
      /** Co Benefit Defaults */
      co_benefit_defaults: {
        [key: string]: string;
      };
      /** Display Name */
      display_name: string;
      /**
       * Evidence Confidence
       * @enum {string}
       */
      evidence_confidence: 'low' | 'medium' | 'high';
      /**
       * Evidence Provenance
       * @enum {string}
       */
      evidence_provenance: 'existing' | 'new' | 'derived';
      /** Family */
      family: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: 'element' | 'composite';
      /** Nbs Id */
      nbs_id: string;
      /** Nbs Type */
      nbs_type: string;
      /** Notes */
      notes?: string | null;
      /** Output Caveats */
      output_caveats?: string[];
      /** Primary Cooling Mechanism */
      primary_cooling_mechanism: string;
      /** Sources */
      sources: components['schemas']['Source'][];
      suitability: components['schemas']['Suitability'];
      /** Suitability Inherited */
      suitability_inherited: boolean;
      /** Temp Reduction Max C */
      temp_reduction_max_c: number;
      /** Temp Reduction Min C */
      temp_reduction_min_c: number;
      /** Typical Use Context */
      typical_use_context: string[];
    };
    /**
     * TypologyEntry
     * @description One catalogue entry, as written in ``nbs_typologies.yaml``.
     */
    TypologyEntry: {
      /** Archetype */
      archetype: string;
      availability: components['schemas']['Availability'];
      /** Display Name */
      display_name: string;
      /** Family */
      family: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: 'element' | 'composite';
      /** Nbs Id */
      nbs_id: string;
      /** Nbs Type */
      nbs_type: string;
      /** Notes */
      notes?: string | null;
      /** Primary Cooling Mechanism */
      primary_cooling_mechanism: string;
      suitability_overrides?: components['schemas']['SuitabilityOverride'] | null;
    };
    /**
     * TypologyLibrary
     * @description The complete typology library, as loaded from ``nbs_typologies.yaml``.
     *
     *     ``archetypes`` and ``typologies`` are the file as written; ``resolved`` is
     *     the flat scoring view, computed once at load.
     */
    TypologyLibrary: {
      /** Archetypes */
      archetypes: components['schemas']['Archetype'][];
      /** Resolved */
      resolved?: components['schemas']['Typology'][];
      /** Typologies */
      typologies: components['schemas']['TypologyEntry'][];
      /** Version */
      version: string;
    };
    /**
     * TypologySummary
     * @description The library values one component was computed against.
     *
     *     ``archetype`` and ``evidence_provenance`` are reported alongside the
     *     values, because under the archetype model (D-044) an entry inherits a
     *     *cited* envelope and the result must name the evidence class it inherited
     *     from — a Miyawaki forest reports its cooling on the dense-canopy evidence,
     *     and says so.
     */
    TypologySummary: {
      /** Archetype */
      archetype: string;
      /** Archetype Display Name */
      archetype_display_name: string;
      /** Base Cooling Score */
      base_cooling_score: number;
      /** Building Energy Applicable */
      building_energy_applicable: boolean;
      /**
       * Category
       * @enum {string}
       */
      category: 'green' | 'building' | 'blue_green' | 'hybrid';
      /** Display Name */
      display_name: string;
      /**
       * Evidence Confidence
       * @enum {string}
       */
      evidence_confidence: 'low' | 'medium' | 'high';
      /**
       * Evidence Provenance
       * @enum {string}
       */
      evidence_provenance: 'existing' | 'new' | 'derived';
      /** Family */
      family: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: 'element' | 'composite';
      /** Nbs Id */
      nbs_id: string;
      /** Nbs Type */
      nbs_type: string;
      /** Suitability Inherited */
      suitability_inherited: boolean;
      /** Temp Reduction Max C */
      temp_reduction_max_c: number;
      /** Temp Reduction Min C */
      temp_reduction_min_c: number;
    };
    /**
     * ValidateResponse
     * @description ``POST /api/assessments/validate`` (D-028).
     *
     *     Exactly two severities exist (OQ-08): ``errors`` block progression within
     *     their step, ``warnings`` never block. Warning texts are the engine's own.
     */
    ValidateResponse: {
      confidence: components['schemas']['ConfidencePreview'];
      /** Errors */
      errors: components['schemas']['FieldIssue'][];
      /** Valid */
      valid: boolean;
      /** Warnings */
      warnings: string[];
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /**
     * VulnerabilityBlock
     * @description Vulnerability Score (Methodology Report 5.2).
     */
    VulnerabilityBlock: {
      /** Score */
      score: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  evaluate_api_assessments_evaluate_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AssessmentInput'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AssessmentResult'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  validate_api_assessments_validate_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ValidateResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  basemap_api_geo_basemap_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  lookup_api_geo_lookup_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GeoLookupRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GeoLookupResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  places_api_geo_places_get: {
    parameters: {
      query: {
        query: string;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PlaceSearchResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  meta_api_meta_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MetaResponse'];
        };
      };
    };
  };
  methodology_api_methodology_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  list_projects_api_projects_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectSummary'][];
        };
      };
    };
  };
  create_project_api_projects_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProjectCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_project_api_projects__project_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_project_api_projects__project_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_project_api_projects__project_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProjectPatch'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_assessment_api_projects__project_id__assessments_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AssessmentCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AssessmentView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_assessment_api_projects__project_id__assessments__assessment_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        assessment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AssessmentView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_assessment_api_projects__project_id__assessments__assessment_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        assessment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_assessment_api_projects__project_id__assessments__assessment_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        assessment_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AssessmentPatch'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AssessmentView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  duplicate_assessment_api_projects__project_id__assessments__assessment_id__duplicate_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        assessment_id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['AssessmentDuplicate'] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AssessmentView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  evaluate_assessment_api_projects__project_id__assessments__assessment_id__evaluate_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        assessment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AssessmentView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  report_pdf_api_projects__project_id__assessments__assessment_id__report_pdf_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        assessment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/octet-stream': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  report_xlsx_api_projects__project_id__assessments__assessment_id__report_xlsx_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        assessment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/octet-stream': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  typologies_api_typologies_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TypologyLibrary'];
        };
      };
    };
  };
  available_api_typologies_available_get: {
    parameters: {
      query: {
        assessment_scale: 'city' | 'district' | 'neighbourhood' | 'site' | 'building';
        land_use?: string | null;
        waterfront_type?: ('lake' | 'river' | 'dry_river' | 'covered_river' | 'sea') | null;
        includes_railway?: boolean | null;
        existing_woodland?: boolean | null;
        productive_governance?:
          ('community' | 'individual' | 'institutional' | 'commercial')[] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AvailableTypologies'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
