/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/assessments/evaluate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Evaluate
     * @description Validate the input, run the engine, return the full result.
     *
     *     Stateless and deterministic: an identical request body against an
     *     identical methodology version yields a byte-identical response body.
     */
    post: operations['evaluate_api_assessments_evaluate_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/assessments/validate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Validate
     * @description Dry-run validation of a partial questionnaire state (D-028).
     */
    post: operations['validate_api_assessments_validate_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/meta': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Meta
     * @description Engine version, methodology version, and licence.
     */
    get: operations['meta_api_meta_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/methodology': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Methodology
     * @description Formulas, weights, factors, and defaults, with the methodology version.
     */
    get: operations['methodology_api_methodology_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Projects
     * @description All projects, most recently updated first.
     */
    get: operations['list_projects_api_projects_get'];
    put?: never;
    /** Create Project */
    post: operations['create_project_api_projects_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{project_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Project */
    get: operations['get_project_api_projects__project_id__get'];
    put?: never;
    post?: never;
    /** Delete Project */
    delete: operations['delete_project_api_projects__project_id__delete'];
    options?: never;
    head?: never;
    /** Update Project */
    patch: operations['update_project_api_projects__project_id__patch'];
    trace?: never;
  };
  '/api/projects/{project_id}/assessments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Assessment */
    post: operations['create_assessment_api_projects__project_id__assessments_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{project_id}/assessments/{assessment_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Assessment */
    get: operations['get_assessment_api_projects__project_id__assessments__assessment_id__get'];
    put?: never;
    post?: never;
    /** Delete Assessment */
    delete: operations['delete_assessment_api_projects__project_id__assessments__assessment_id__delete'];
    options?: never;
    head?: never;
    /** Update Assessment */
    patch: operations['update_assessment_api_projects__project_id__assessments__assessment_id__patch'];
    trace?: never;
  };
  '/api/projects/{project_id}/assessments/{assessment_id}/duplicate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Duplicate Assessment
     * @description Create a comparison draft from an existing assessment (D-021).
     */
    post: operations['duplicate_assessment_api_projects__project_id__assessments__assessment_id__duplicate_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{project_id}/assessments/{assessment_id}/evaluate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Evaluate Assessment
     * @description Run the engine on the stored draft input and persist the result.
     *
     *     An explicit user action (OQ-15): refused once a result exists, because a
     *     stored result is never recomputed — re-running means creating a new
     *     assessment.
     */
    post: operations['evaluate_assessment_api_projects__project_id__assessments__assessment_id__evaluate_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{project_id}/assessments/{assessment_id}/report.pdf': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Report Pdf
     * @description The 2-page PDF report of a stored, evaluated assessment.
     */
    get: operations['report_pdf_api_projects__project_id__assessments__assessment_id__report_pdf_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{project_id}/assessments/{assessment_id}/report.xlsx': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Report Xlsx
     * @description The XLSX workbook (Inputs, Results, Assumptions & Warnings).
     */
    get: operations['report_xlsx_api_projects__project_id__assessments__assessment_id__report_xlsx_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/typologies': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Typologies
     * @description The NbS typology library, including suitability conditions and citations.
     */
    get: operations['typologies_api_typologies_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AdjustmentBlock
     * @description Site adjustment factor and its four derived conditions (5.4).
     */
    AdjustmentBlock: {
      canopy: components['schemas']['AdjustmentCondition'];
      climate: components['schemas']['AdjustmentCondition'];
      /** Factor */
      factor: number;
      scale: components['schemas']['AdjustmentCondition'];
      soil_water: components['schemas']['AdjustmentCondition'];
    };
    /**
     * AdjustmentCondition
     * @description One derived site condition and the factor it resolved to.
     */
    AdjustmentCondition: {
      /** Detail */
      detail?: string | null;
      /** Factor */
      factor: number;
      /**
       * Level
       * @enum {string}
       */
      level: 'poor' | 'moderate' | 'good' | 'excellent' | 'unknown';
    };
    /** AssessmentCreate */
    AssessmentCreate: {
      /** Input */
      input?: {
        [key: string]: unknown;
      };
      /** Label */
      label: string;
    };
    /** AssessmentDuplicate */
    AssessmentDuplicate: {
      /** Label */
      label?: string | null;
    };
    /**
     * AssessmentInput
     * @description One site plus one proposed NbS intervention, as described by the user.
     *
     *     Required fields are those without which a documented formula cannot be
     *     evaluated at all; everything else is optional, and absence reduces
     *     confidence but never blocks the assessment.
     */
    AssessmentInput: {
      /** Access To Cooled Indoor Space */
      access_to_cooled_indoor_space?: ('low' | 'medium' | 'high' | 'unknown') | null;
      /** Annual Cooling Energy Demand Kwh */
      annual_cooling_energy_demand_kwh?: number | null;
      /**
       * Assessment Scale
       * @enum {string}
       */
      assessment_scale: 'city' | 'district' | 'neighbourhood' | 'site' | 'building';
      /** Capital Cost */
      capital_cost?: number | null;
      /**
       * Climate Zone
       * @enum {string}
       */
      climate_zone: 'tropical_wet' | 'tropical_dry' | 'arid' | 'semi_arid' | 'temperate' | 'other';
      /** Co Benefit Biodiversity */
      co_benefit_biodiversity?: ('low' | 'medium' | 'high' | 'very_high' | 'unknown') | null;
      /** Co Benefit Public Health */
      co_benefit_public_health?: ('low' | 'medium' | 'high' | 'very_high' | 'unknown') | null;
      /** Co Benefit Social Inclusion */
      co_benefit_social_inclusion?: ('low' | 'medium' | 'high' | 'very_high' | 'unknown') | null;
      /** Co Benefit Stormwater */
      co_benefit_stormwater?: ('low' | 'medium' | 'high' | 'very_high' | 'unknown') | null;
      /** Co Benefit Urban Quality */
      co_benefit_urban_quality?: ('low' | 'medium' | 'high' | 'very_high' | 'unknown') | null;
      /** Community Participation */
      community_participation?: ('low' | 'medium' | 'high' | 'very_high' | 'unknown') | null;
      /** Country */
      country?: string | null;
      /** Currency */
      currency?: string | null;
      /** Current Shade Level */
      current_shade_level?: ('very_low' | 'low' | 'medium' | 'high' | 'unknown') | null;
      /** Energy Price Per Kwh */
      energy_price_per_kwh?: number | null;
      /** Existing Green Cover Percent */
      existing_green_cover_percent?: number | null;
      /** Existing Tree Canopy Percent */
      existing_tree_canopy_percent?: number | null;
      /** Expected Maturity Period Years */
      expected_maturity_period_years?: number | null;
      /** Grid Emission Factor Kgco2E Per Kwh */
      grid_emission_factor_kgco2e_per_kwh?: number | null;
      /** Heat Exposure Level */
      heat_exposure_level?: ('low' | 'medium' | 'high' | 'very_high' | 'unknown') | null;
      /** Heat Index Concern */
      heat_index_concern?: ('low' | 'medium' | 'high' | 'very_high' | 'unknown') | null;
      /** Impervious Surface Percent */
      impervious_surface_percent?: number | null;
      /** Implementation Complexity */
      implementation_complexity?: ('low' | 'medium' | 'high' | 'unknown') | null;
      /** Intervention Area M2 */
      intervention_area_m2?: number | null;
      /** Irrigation Availability */
      irrigation_availability?: ('none' | 'occasional' | 'reliable' | 'unknown') | null;
      /** Land Use */
      land_use?:
        | (
            | 'street_corridor'
            | 'residential'
            | 'mixed_use'
            | 'commercial'
            | 'public_space'
            | 'park'
            | 'school'
            | 'healthcare'
            | 'industrial'
            | 'other'
          )
        | null;
      /** Lst Anomaly C */
      lst_anomaly_c?: number | null;
      /** Maintenance Intensity */
      maintenance_intensity?: ('low' | 'medium' | 'high' | 'unknown') | null;
      /** Nbs Type */
      nbs_type: string;
      /** Nearby Building Cooling Demand Relevant */
      nearby_building_cooling_demand_relevant?: ('yes' | 'no' | 'unknown') | null;
      /** New Canopy Area At Maturity M2 */
      new_canopy_area_at_maturity_m2?: number | null;
      /** Population Density */
      population_density?: ('low' | 'medium' | 'high' | 'very_high' | 'unknown') | null;
      /** Project Name */
      project_name?: string | null;
      /** Public Accessibility */
      public_accessibility?: ('low' | 'medium' | 'high' | 'very_high' | 'unknown') | null;
      /** Safety Concern */
      safety_concern?: ('low' | 'medium' | 'high' | 'very_high' | 'unknown') | null;
      /** Site Area M2 */
      site_area_m2: number;
      /** Soil Availability */
      soil_availability?: ('none' | 'limited' | 'moderate' | 'high' | 'unknown') | null;
      /** Solar Exposure */
      solar_exposure?: ('low' | 'medium' | 'high' | 'very_high' | 'unknown') | null;
      /** Vulnerable Population Presence */
      vulnerable_population_presence?: ('low' | 'medium' | 'high' | 'very_high' | 'unknown') | null;
    };
    /** AssessmentPatch */
    AssessmentPatch: {
      /** Input */
      input?: {
        [key: string]: unknown;
      } | null;
      /** Label */
      label?: string | null;
    };
    /**
     * AssessmentResult
     * @description Everything the engine reports for one assessment run.
     */
    AssessmentResult: {
      adjustment: components['schemas']['AdjustmentBlock'];
      /** Assumptions Applied */
      assumptions_applied: string[];
      co_benefits: components['schemas']['CoBenefitsBlock'];
      confidence: components['schemas']['ConfidenceBlock'];
      cooling: components['schemas']['CoolingBlock'];
      costs: components['schemas']['CostsBlock'];
      energy: components['schemas']['EnergyBlock'];
      /** Engine Version */
      engine_version: string;
      equity: components['schemas']['EquityBlock'];
      ghg: components['schemas']['GhgBlock'];
      heat_exposure: components['schemas']['HeatExposureBlock'];
      heat_priority: components['schemas']['HeatPriorityBlock'];
      /** Method Note */
      method_note: string;
      /** Methodology Version */
      methodology_version: string;
      opportunity: components['schemas']['OpportunityBlock'];
      /** Recommendation */
      recommendation: string;
      suitability: components['schemas']['SuitabilityBlock'];
      typology: components['schemas']['TypologySummary'];
      vulnerability: components['schemas']['VulnerabilityBlock'];
      /** Warnings */
      warnings: string[];
    };
    /**
     * AssessmentView
     * @description A stored assessment plus the OQ-15 surfacing flag.
     *
     *     ``methodology_update_available`` is true when the stored result was
     *     produced under an older methodology version than the one currently loaded.
     *     The stored result itself is never recomputed; re-running is an explicit
     *     user action that creates a new assessment.
     */
    AssessmentView: {
      /** Assessment Id */
      assessment_id: string;
      /** Created At */
      created_at: string;
      /** Input */
      input: {
        [key: string]: unknown;
      };
      /** Label */
      label: string;
      /** Methodology Update Available */
      methodology_update_available: boolean;
      /** Result */
      result?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * BlockConfidencePreview
     * @description Live confidence for one output block (UX specification section 4).
     */
    BlockConfidencePreview: {
      /** Completeness Percent */
      completeness_percent: number;
      hint: components['schemas']['ConfidenceHint'] | null;
      /**
       * Level
       * @enum {string}
       */
      level: 'low' | 'medium' | 'high';
    };
    /**
     * CoBenefitsBlock
     * @description Co-benefit Score and its five sub-indicators.
     */
    CoBenefitsBlock: {
      /** Biodiversity */
      biodiversity: number;
      /** Public Health */
      public_health: number;
      /** Score */
      score: number;
      /** Social Inclusion */
      social_inclusion: number;
      /** Stormwater */
      stormwater: number;
      /** Urban Quality */
      urban_quality: number;
    };
    /**
     * ConfidenceBlock
     * @description Branched per-block confidence (D-011/OQ-09, D-024).
     */
    ConfidenceBlock: {
      /** Completeness Percent */
      completeness_percent: {
        [key: string]: number;
      };
      /**
       * Cooling
       * @enum {string}
       */
      cooling: 'low' | 'medium' | 'high';
      /** Cooling Capped By Evidence */
      cooling_capped_by_evidence: boolean;
      /**
       * Economic
       * @enum {string}
       */
      economic: 'low' | 'medium' | 'high';
      /**
       * Energy
       * @enum {string}
       */
      energy: 'low' | 'medium' | 'high';
      /**
       * Equity
       * @enum {string}
       */
      equity: 'low' | 'medium' | 'high';
      /**
       * Overall
       * @enum {string}
       */
      overall: 'low' | 'medium' | 'high';
    };
    /**
     * ConfidenceHint
     * @description The highest-value missing field group for one block (D-028).
     *
     *     ``fields`` lists the group's alternative fields (usually one; the heat
     *     signal slot offers two). ``raises_level_to`` is the level the block reaches
     *     if any of them is answered, or ``None`` when no single completion raises
     *     the level and the group is simply the first unsupplied one in configured
     *     order.
     */
    ConfidenceHint: {
      /** Fields */
      fields: string[];
      /** Raises Level To */
      raises_level_to: ('low' | 'medium' | 'high') | null;
    };
    /**
     * ConfidencePreview
     * @description Per-block confidence preview, computed by ``nature_cooling.engine.confidence``.
     */
    ConfidencePreview: {
      cooling: components['schemas']['BlockConfidencePreview'];
      /** Cooling Capped By Evidence */
      cooling_capped_by_evidence: boolean;
      economic: components['schemas']['BlockConfidencePreview'];
      energy: components['schemas']['BlockConfidencePreview'];
      equity: components['schemas']['BlockConfidencePreview'];
      /**
       * Overall
       * @enum {string}
       */
      overall: 'low' | 'medium' | 'high';
    };
    /**
     * CoolingBlock
     * @description Cooling Potential Score and clipped temperature range (5.5, D-008).
     */
    CoolingBlock: {
      /** Delta T Max C */
      delta_t_max_c: number;
      /** Delta T Midpoint C */
      delta_t_midpoint_c: number;
      /** Delta T Min C */
      delta_t_min_c: number;
      /**
       * Heat Index Improvement
       * @enum {string}
       */
      heat_index_improvement: 'low' | 'medium' | 'high';
      /** Potential Score */
      potential_score: number;
      /** Shade Potential Percent */
      shade_potential_percent: number | null;
      /**
       * Shade Potential Status
       * @enum {string}
       */
      shade_potential_status: 'calculated' | 'not_estimated';
      /** Time To Benefit */
      time_to_benefit: ('immediate' | 'short_term' | 'medium_term' | 'long_term') | null;
      /**
       * Time To Benefit Status
       * @enum {string}
       */
      time_to_benefit_status: 'derived' | 'not_estimated';
    };
    /**
     * CostsBlock
     * @description Cost outputs: savings, payback, derived feasibility, readiness (5.8).
     */
    CostsBlock: {
      /** Annual Savings Max */
      annual_savings_max: number | null;
      /** Annual Savings Min */
      annual_savings_min: number | null;
      /**
       * Annual Savings Status
       * @enum {string}
       */
      annual_savings_status: 'calculated' | 'energy_not_calculated' | 'missing_energy_price';
      /** Cost Feasibility Score */
      cost_feasibility_score: number | null;
      /**
       * Cost Feasibility Status
       * @enum {string}
       */
      cost_feasibility_status: 'derived' | 'not_estimated';
      /** Currency */
      currency: string | null;
      /** Investment Readiness */
      investment_readiness: ('low' | 'medium' | 'high') | null;
      /**
       * Investment Readiness Status
       * @enum {string}
       */
      investment_readiness_status: 'derived' | 'not_estimated';
      /** Payback Bracket */
      payback_bracket: ('short' | 'medium' | 'long' | 'very_long') | null;
      /**
       * Payback Status
       * @enum {string}
       */
      payback_status: 'calculated' | 'missing_capital_cost' | 'annual_savings_unavailable';
      /** Payback Years Central */
      payback_years_central: number | null;
      /** Payback Years Max */
      payback_years_max: number | null;
      /** Payback Years Min */
      payback_years_min: number | null;
    };
    /**
     * EnergyBlock
     * @description Derived cooling-energy savings (5.6, D-015).
     */
    EnergyBlock: {
      /** Savings Max Kwh Per Year */
      savings_max_kwh_per_year: number | null;
      /** Savings Min Kwh Per Year */
      savings_min_kwh_per_year: number | null;
      /**
       * Status
       * @enum {string}
       */
      status:
        | 'calculated'
        | 'not_applicable'
        | 'missing_energy_demand'
        | 'typology_not_applicable'
        | 'relevance_not_confirmed';
      /** Status Message */
      status_message: string;
    };
    /**
     * EquityBlock
     * @description Equity Score (reported with its own confidence; not aggregated).
     *
     *     The Equity Score deliberately does not enter the final aggregation:
     *     equity influences the headline score through the Vulnerability Score
     *     instead. This is disclosed in the Methodology Report.
     */
    EquityBlock: {
      /** Participation Relevance */
      participation_relevance: number;
      /** Public Accessibility */
      public_accessibility: number;
      /** Safety Comfort */
      safety_comfort: number;
      /** Score */
      score: number;
      /** Vulnerable User Benefit */
      vulnerable_user_benefit: number;
    };
    /**
     * FieldIssue
     * @description One validation error, addressed to the form field it belongs to.
     */
    FieldIssue: {
      /** Field */
      field: string;
      /** Message */
      message: string;
    };
    /**
     * GhgBlock
     * @description Greenhouse gas emissions avoided (5.7).
     */
    GhgBlock: {
      /** Avoided Max Kgco2E Per Year */
      avoided_max_kgco2e_per_year: number | null;
      /** Avoided Min Kgco2E Per Year */
      avoided_min_kgco2e_per_year: number | null;
      /** Emission Factor Kgco2E Per Kwh */
      emission_factor_kgco2e_per_kwh: number | null;
      /** Emission Factor Origin */
      emission_factor_origin: ('user_supplied' | 'country_default') | null;
      /**
       * Status
       * @enum {string}
       */
      status: 'calculated' | 'missing_emission_factor' | 'energy_not_calculated';
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /**
     * HeatExposureBlock
     * @description Heat Exposure Score (Methodology Report 5.1).
     */
    HeatExposureBlock: {
      /**
       * Path
       * @enum {string}
       */
      path: 'data_rich' | 'data_poor';
      /** Score */
      score: number;
    };
    /**
     * HeatPriorityBlock
     * @description Heat Priority Index (Methodology Report 5.3).
     */
    HeatPriorityBlock: {
      /**
       * Category
       * @enum {string}
       */
      category: 'low' | 'medium' | 'high' | 'critical';
      /** Score */
      score: number;
    };
    /**
     * MetaResponse
     * @description ``GET /api/meta``.
     */
    MetaResponse: {
      /** Engine Version */
      engine_version: string;
      /** License */
      license: string;
      /** Methodology Version */
      methodology_version: string;
    };
    /**
     * OpportunityBlock
     * @description NbS Cooling Opportunity Score (5.9), with full weight transparency.
     */
    OpportunityBlock: {
      /**
       * Category
       * @enum {string}
       */
      category: 'low' | 'moderate' | 'strong' | 'high_priority';
      /** Components */
      components: components['schemas']['OpportunityComponent'][];
      /** Excluded Components */
      excluded_components: string[];
      /** Score */
      score: number;
    };
    /**
     * OpportunityComponent
     * @description One component of the final aggregation, with the weight applied.
     */
    OpportunityComponent: {
      /** Applied Weight */
      applied_weight: number;
      /** Name */
      name: string;
      /** Nominal Weight */
      nominal_weight: number;
      /** Score */
      score: number;
    };
    /** ProjectCreate */
    ProjectCreate: {
      /** Name */
      name: string;
      /** Site */
      site?: {
        [key: string]: unknown;
      };
    };
    /** ProjectPatch */
    ProjectPatch: {
      /** Name */
      name?: string | null;
      /** Site */
      site?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * ProjectSummary
     * @description ``GET /api/projects`` list entry.
     */
    ProjectSummary: {
      /** Assessment Count */
      assessment_count: number;
      /** Created At */
      created_at: string;
      /** Name */
      name: string;
      /** Project Id */
      project_id: string;
      /** Updated At */
      updated_at: string;
    };
    /**
     * ProjectView
     * @description A project document plus the current methodology version, for OQ-15.
     */
    ProjectView: {
      /** Assessments */
      assessments: components['schemas']['AssessmentView'][];
      /** Created At */
      created_at: string;
      /** Current Methodology Version */
      current_methodology_version: string;
      /** Name */
      name: string;
      /** Project Id */
      project_id: string;
      /** Schema Version */
      schema_version: number;
      /** Site */
      site: {
        [key: string]: unknown;
      };
      /** Updated At */
      updated_at: string;
    };
    /**
     * Source
     * @description A citation supporting a configuration value.
     */
    Source: {
      /** Finding */
      finding: string;
      /** Key */
      key: string;
    };
    /**
     * Suitability
     * @description Conditions under which a typology is considered unsuitable for a site.
     */
    Suitability: {
      /** Minimum Site Area M2 */
      minimum_site_area_m2: number;
      /**
       * Requires Irrigation
       * @enum {string}
       */
      requires_irrigation: 'none' | 'occasional' | 'reliable';
      /**
       * Requires Soil
       * @enum {string}
       */
      requires_soil: 'none' | 'limited' | 'moderate' | 'high';
      /** Unsuitable Climate Zones */
      unsuitable_climate_zones?: string[];
    };
    /**
     * SuitabilityBlock
     * @description NbS Suitability Score, its sub-indicators, and hard flags (D-022).
     */
    SuitabilityBlock: {
      /** Flags */
      flags: components['schemas']['SuitabilityFlag'][];
      /** Maintenance */
      maintenance: number;
      /** Score */
      score: number;
      /** Soil */
      soil: number;
      /** Space */
      space: number;
      /** Suitable */
      suitable: boolean;
      /** Urban Context */
      urban_context: number;
      /** Water */
      water: number;
    };
    /**
     * SuitabilityFlag
     * @description A hard 'not suitable for this site' condition (D-009).
     */
    SuitabilityFlag: {
      /**
       * Code
       * @enum {string}
       */
      code:
        | 'below_minimum_area'
        | 'insufficient_soil'
        | 'insufficient_irrigation'
        | 'unsuitable_climate';
      /** Message */
      message: string;
    };
    /**
     * Typology
     * @description One NbS typology and its literature-grounded performance assumptions.
     */
    Typology: {
      /** Base Cooling Score */
      base_cooling_score: number;
      /** Building Energy Applicable */
      building_energy_applicable: boolean;
      /**
       * Category
       * @enum {string}
       */
      category: 'green' | 'building' | 'blue_green' | 'hybrid';
      /** Co Benefit Defaults */
      co_benefit_defaults: {
        [key: string]: string;
      };
      /** Display Name */
      display_name: string;
      /**
       * Evidence Confidence
       * @enum {string}
       */
      evidence_confidence: 'low' | 'medium' | 'high';
      /** Nbs Id */
      nbs_id: string;
      /** Nbs Type */
      nbs_type: string;
      /** Notes */
      notes?: string | null;
      /** Output Caveats */
      output_caveats?: string[];
      /** Primary Cooling Mechanism */
      primary_cooling_mechanism: string;
      /** Sources */
      sources: components['schemas']['Source'][];
      suitability: components['schemas']['Suitability'];
      /** Temp Reduction Max C */
      temp_reduction_max_c: number;
      /** Temp Reduction Min C */
      temp_reduction_min_c: number;
      /** Typical Use Context */
      typical_use_context: string[];
    };
    /**
     * TypologyLibrary
     * @description The complete typology library, as loaded from ``nbs_typologies.yaml``.
     */
    TypologyLibrary: {
      /** Typologies */
      typologies: components['schemas']['Typology'][];
      /** Version */
      version: string;
    };
    /**
     * TypologySummary
     * @description The library values the assessment was computed against.
     */
    TypologySummary: {
      /** Base Cooling Score */
      base_cooling_score: number;
      /**
       * Category
       * @enum {string}
       */
      category: 'green' | 'building' | 'blue_green' | 'hybrid';
      /** Display Name */
      display_name: string;
      /**
       * Evidence Confidence
       * @enum {string}
       */
      evidence_confidence: 'low' | 'medium' | 'high';
      /** Nbs Id */
      nbs_id: string;
      /** Nbs Type */
      nbs_type: string;
      /** Temp Reduction Max C */
      temp_reduction_max_c: number;
      /** Temp Reduction Min C */
      temp_reduction_min_c: number;
    };
    /**
     * ValidateResponse
     * @description ``POST /api/assessments/validate`` (D-028).
     *
     *     Exactly two severities exist (OQ-08): ``errors`` block progression within
     *     their step, ``warnings`` never block. Warning texts are the engine's own.
     */
    ValidateResponse: {
      confidence: components['schemas']['ConfidencePreview'];
      /** Errors */
      errors: components['schemas']['FieldIssue'][];
      /** Valid */
      valid: boolean;
      /** Warnings */
      warnings: string[];
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /**
     * VulnerabilityBlock
     * @description Vulnerability Score (Methodology Report 5.2).
     */
    VulnerabilityBlock: {
      /** Score */
      score: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  evaluate_api_assessments_evaluate_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AssessmentInput'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AssessmentResult'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  validate_api_assessments_validate_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ValidateResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  meta_api_meta_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MetaResponse'];
        };
      };
    };
  };
  methodology_api_methodology_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  list_projects_api_projects_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectSummary'][];
        };
      };
    };
  };
  create_project_api_projects_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProjectCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_project_api_projects__project_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_project_api_projects__project_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_project_api_projects__project_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProjectPatch'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProjectView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_assessment_api_projects__project_id__assessments_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AssessmentCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AssessmentView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_assessment_api_projects__project_id__assessments__assessment_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        assessment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AssessmentView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_assessment_api_projects__project_id__assessments__assessment_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        assessment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_assessment_api_projects__project_id__assessments__assessment_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        assessment_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AssessmentPatch'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AssessmentView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  duplicate_assessment_api_projects__project_id__assessments__assessment_id__duplicate_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        assessment_id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['AssessmentDuplicate'] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AssessmentView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  evaluate_assessment_api_projects__project_id__assessments__assessment_id__evaluate_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        assessment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AssessmentView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  report_pdf_api_projects__project_id__assessments__assessment_id__report_pdf_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        assessment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/octet-stream': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  report_xlsx_api_projects__project_id__assessments__assessment_id__report_xlsx_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
        assessment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/octet-stream': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  typologies_api_typologies_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TypologyLibrary'];
        };
      };
    };
  };
}
